### ISSUE TITLE
Feature Request: Add --version and -v info.

### ISSUE THREAD

**Issue by aaronliu0130** [stefanhaustein/TerminalImageViewer#84]
There currently is no --version or -v info whatsoever. I suggest adding it, and it should say the version along with info of the OS.

**Comment by stefanhaustein** [comment]
A version number is now included in the general help page without any flag... Do you think that's not sufficient?

**Comment by aaronliu0130** [comment]
> A version number is now included in the general help page without any flag... Do you think that's not sufficient?

```$ tiv --help
Terminal Image Viewer

usage: tiv [options] <image> [<image>...]

  -0        : No block character adjustment, always use top half block char.
  -256      : Use 256 color mode.
  -c <num>  : Number of thumbnail columns in 'dir' mode (3).
  -d        : Force 'dir' mode. Automatially selected for more than one input.
  -f        : Force 'full' mode. Automatically selected for one input.
  -help     : Display this help text.
  -h <num>  : Set the maximum height to <num> lines.
  -w <num>  : Set the maximum width to <num> characters.
```
I dunno why, but I see no version number.

**Comment by aaronliu0130** [comment]
It might be that my installation was too early. Even if there was, I suggest adding OS info to the help page or maybe add a dedicated --version command. OS info can be like this:
```cpp
std::string getOsName()
{
    #ifdef _WIN64
    return "Windows 64-bit";
    #elif _WIN32
    return "Windows 32-bit";
    #elif __APPLE__ || __MACH__
    return "Mac OSX";
    #elif __linux__
    return "Linux";
    #elif __FreeBSD__
    return "FreeBSD";
    #elif __unix || __unix__
    return "Unix";
    #else
    return "Other";
    #endif
} 
```

**Comment by rubyFeedback** [comment]
Hey there Stefan,

I am a ruby guy; I noticed some .rb file. :D

I am not the original author, but I agree with his comment.

The reason why I think a version flag would be useful is because
I batch-query different programs. So to know the version, 
having the binary support -v or --version or anything is helpful.

That way I can query the current version, compare it to a
list of installed programs, and if a remote update to the
code exists (e. g. at the github page here, or elsewhere),
I can notify the user about it.

This may not be a "common usage pattern" admittedly 
so, but I think it is one additional reason why direct support
for version would be very useful, IMO.

Edit: Actually I just re-read your statement here:

> A version number is now included in the general help page without any flag... Do you
> think that's not sufficient?

So you are right in my case; I can just ask ruby to query --help and find the corresponding
version number, so no big deal for me. I think having --version available may still be
useful though, e. g. that way people may not have to query --help and find what they
are looking for. But my described use case is satisfied with the -help variant also
showing the version.
